name: Deploy to Firebase Hosting on merge
on:
  workflow_run:
    workflows: [ Qodana ]
    types: [ completed ]
    branches: [ master ]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEMONPFTEST }}
          channelId: live
          projectId: wemonpftest
