name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: 'CodeQL Scan'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: qodana.sarif.json
      - uses: actions/checkout@v4
      - run: npm ci
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3
        with:
          args: --config=qodana.yaml,--baseline,qodana.sarif.json,--fail-threshold,0
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1450278944 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'

