name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3
        with:
          args: --config=qodana.yaml
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1450278944 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'

